displayName=Ali Morrisane Values
author=20pc Nugget
description=Displays the value of runes in your inventory and rune pouch if sold to Ali Morrisane.
version=1
plugins=com.alimorrisanevalues.AliMorrisaneValuesPlugin
build=standard